### ISSUE TITLE
PHP7.2 throws errors in concrete/core/controllers/blocks/form.php

### ISSUE THREAD

**Issue by weyboat** [concrete5/concrete5-legacy#1987]
The full error message is:
Warning: count(): Parameter must be an array or an object that implements Countable in /concrete/core/controllers/blocks/form.php on line 310

Warning: count(): Parameter must be an array or an object that implements Countable in /concrete/core/controllers/blocks/form.php on line 345

Warning: Use of undefined constant FORM_BLOCK_SENDER_EMAIL - assumed 'FORM_BLOCK_SENDER_EMAIL' (this will throw an Error in a future version of PHP) in /concrete/core/controllers/blocks/form.php on line 362

Warning: Use of undefined constant FORM_BLOCK_SENDER_EMAIL - assumed 'FORM_BLOCK_SENDER_EMAIL' (this will throw an Error in a future version of PHP) in /concrete/core/controllers/blocks/form.php on line 362

Warning: Use of undefined constant FORM_BLOCK_SENDER_EMAIL - assumed 'FORM_BLOCK_SENDER_EMAIL' (this will throw an Error in a future version of PHP) in /concrete/core/controllers/blocks/form.php on line 445

Warning: Use of undefined constant FORM_BLOCK_SENDER_EMAIL - assumed 'FORM_BLOCK_SENDER_EMAIL' (this will throw an Error in a future version of PHP) in /concrete/core/controllers/blocks/form.php on line 445

**Comment by weyboat** [comment]
#1988 doesn't appear to address the countable errors, I have fixed those errors in the file I attached..

**Comment by mlocati** [comment]
> The attached file fixes these errors
> 
> [form.zip](https://github.com/concrete5/concrete5-legacy/files/2440777/form.zip)

@weyboat Nope, your fix is not correct. Let me explain what's happening.

We have this PHP code:
```php
if(strlen(FORM_BLOCK_SENDER_EMAIL)>1 && strstr(FORM_BLOCK_SENDER_EMAIL,'@') ){
```
which means
```
if (the PHP constant named FORM_BLOCK_SENDER_EMAIL has a length greater that 1 and it contains the @ character) {
```

your fix is the following:
```php
if( strlen('FORM_BLOCK_SENDER_EMAIL')>1 && strstr('FORM_BLOCK_SENDER_EMAIL','@') ){
```
which means
```
if (the string 'FORM_BLOCK_SENDER_EMAIL' has a length greater that 1 and it contains the @ character) {
```
that's always false (the string `'FORM_BLOCK_SENDER_EMAIL'` doesn't contain the `@` character).

What PHP is telling us with
```
Warning: Use of undefined constant FORM_BLOCK_SENDER_EMAIL
assumed 'FORM_BLOCK_SENDER_EMAIL'
```
is that the constant `FORM_BLOCK_SENDER_EMAIL` is not defined, so PHP assumes it's the string `'FORM_BLOCK_SENDER_EMAIL'`.
The correct fix (what I implemented in #1988), is to check if the constant `FORM_BLOCK_SENDER_EMAIL` is defined.

**Comment by weyboat** [comment]
Thank you, I have learned something else now..

**Comment by weyboat** [comment]
I just tested your fix and it works for all those errors..

**Comment by weyboat** [comment]
Sorry. I was wrong about your fix.. it doesn't fix the countable errors - I have fixed the countable errors in my file.
I will implement your fix with my countable fix and replace the zip file shortly..

**Comment by mlocati** [comment]
> Sorry. I was wrong about your fix.. it doesn't fix the countable errors

Thanks for hightlighting it, I forgot about this issue. I added https://github.com/concrete5/concrete5-legacy/pull/1988/commits/c041d8ebe0e2c321db06b5814936191208fbd51a to #1988

**Comment by weyboat** [comment]
I just updated the zipped form.php file as well

**Comment by weyboat** [comment]
Your countable fix is prettier than mine so I have removed the zipped file.
